M48
; DRILL file {KiCad 9.0.5} date 2025-12-03T21:16:00-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-03T21:16:00-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X53.6Y-57.1
X53.6Y-147.9
X144.4Y-57.1
X144.4Y-147.9
M30
